### PR TITLE
feat(game): 添加游戏进度保存和加载功能

### PR DESCRIPTION
**Pull request by 51HzOuO**
- 新增 MazeStorage 类用于序列化和反序列化迷宫数据
- 在 ui 类中添加保存和加载游戏进度的逻辑
- 更新 Point 类，使其可序列化
- 优化游戏退出逻辑，提供保存进度的选项

### CODE REVIEW

**Comment by 51HzOuO** [comment]
This pull request includes several changes to add functionality for saving and loading the maze state, as well as some adjustments to the UI behavior. The most important changes include the introduction of a new `MazeStorage` class, modifications to the `ui` class to handle saving and loading the maze state, and making the `Point` class serializable.

### New functionality for saving and loading maze state:

* [`src/MazeStorage.java`](diffhunk://#diff-3e7fc642acc4272ae240a17255bdc1313e7ed610ceeb8ac5dc1cbf80e2c3402eR1-R31): Introduced the `MazeStorage` record to store maze state and added methods to save (`storageMaze`) and load (`getMageStorage`) the maze state from a file.

### UI adjustments for maze state handling:

* [`src/ui.java`](diffhunk://#diff-796ba2772dd59e90db18b0a2b52af2c422eeb43b0c0612e74e9b4921b7a1a965L15-R37): Modified the `ui` constructor to check for existing save files and prompt the user to load the saved state. Added a `WindowListener` to prompt the user to save the maze state on window close. [[1]](diffhunk://#diff-796ba2772dd59e90db18b0a2b52af2c422eeb43b0c0612e74e9b4921b7a1a965L15-R37) [[2]](diffhunk://#diff-796ba2772dd59e90db18b0a2b52af2c422eeb43b0c0612e74e9b4921b7a1a965R49-R73)

### Serialization of `Point` class:

* [`src/utility.java`](diffhunk://#diff-c20551426f0999892592b4e8d0376f87ea83ad5f5ba87105f581c223752f80e6L57-R58): Made the `Point` class implement `Serializable` to support saving and loading the maze state.

**Comment by amazy2596** [comment]
orz

**Comment by 51HzOuO** [comment]
when merge this request

**Comment by 51HzOuO** [comment]
its not bug and conflict

**Comment by 51HzOuO** [comment]
**### 一天了不合并 差评!!!**

**Comment by amazy2596** [comment]
how to merge your code

**Pull request closed without merging**
